[greeter]
theme-name = Greybird-dark
icon-theme-name = Papirus-Dark
font-name = Inter 11
background = /usr/share/backgrounds/aceos/grub.png
user-background = false
indicators = ~host;~spacer;~clock;~spacer;~session;~power
clock-format = %H:%M
position = 50%,center 55%,center
screensaver-timeout = 60
